config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users
  resources :rockets do
    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, only: [ :index, :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rocket
  belongs_to :user

end

app/models/rocket.rb
class Rocket < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, :description, :price, :capacity, :range, :power, :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :description, :price, :address, :capacity, :range, :power ],
    associated_against: {
      bookings: [ :booking_start_date, :booking_end_date, :group_size ]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :rockets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
# before_action :set_rocket, only: [:new, :create]
before_action :set_booking, only: [:destroy]

  def index
    @bookings = current_user.bookings
  end

  def new
    @rocket = Rocket.find(params[:rocket_id])
    @booking = Booking.new
  end

  def create
    @rocket = Rocket.find(params[:rocket_id])
    @booking = Booking.new(booking_params)
    @booking.rocket = @rocket
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

private


  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:booking_start_date, :booking_end_date, :group_size)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_rocket, only: [:show, :update, :edit, :destroy]

  def index
    if params[:query].present?
      @rockets = Rocket.global_search(params[:query])
    else
      @rockets = Rocket.all
    end
    # @rockets = Rocket.where.not(latitude: nil, longitude: nil)
    @markers = @rockets.geocoded.map do |rocket|
      {
        lat: rocket.latitude,
        lng: rocket.longitude,
        info_window: render_to_string(partial: "/rockets/mapbox", locals: { rocket: rocket }),
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @rocket = Rocket.new
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.user = current_user
    @rocket.save!
      redirect_to rocket_path(@rocket)
    # else
    #   render :new
    # end
  end

  def edit
  end

  def update
    if
      @rocket.update(rocket_params)
      redirect_to rocket_path(@rocket)
    else
      render :index
    end
  end

  def destroy
    @rocket.destroy
    redirect_to bookings_path
  end

private

  def set_rocket
    @rocket = Rocket.find(params[:id])
  end

  def rocket_params
    params.require(:rocket).permit(:name, :description, :price, :capacity, :range, :power, :address, :is_available, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-booking">
  <%= simple_form_for [rocket, booking] do |f| %>
    <%= f.input :booking_start_date, as: :date, html5: true %>
    <%= f.input :booking_end_date, as: :date, html5: true  %>
    <%= f.input :group_size, class: 'form-booking-font' %>
    <%= f.submit class: 'btn btn-ghost-booking' %>
    <% end %>
</div>

app/views/bookings/index.html.erb
<main>
  <div class="container booking">
    <div class="row justify-content-center">
    <div class="col-8 sol-sm-8 col-lg-8">
      <h2>My Bookings</h2>
      <div class="bookings-table">
        <table class="table">
          <tr>
          <th class="title-text"> Rocket </th>
          <th class="title-text"> Start Date </th>
          <th class="title-text"> End Date </th>
          <th class="title-text"> Cancel Booking </th>
          </tr>
          <% user_bookings = current_user.bookings %>
          <% user_bookings.each do |booking|%>
          <tr>
          <th class="content-text"> <%= link_to booking.rocket.name, rocket_path(booking.rocket) %> </th>
          <th class="content-text"> <%= booking.booking_start_date %> </th>
          <th class="content-text"> <%= booking.booking_end_date %> </th>
          <th class="content-text"> <%= link_to "Cancel", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class: 'ml-3 text-danger' %> </th>
          </tr>
          <% end %>
        </table>
      </div>

      <div class="my-rockets">
      <h2> My Rockets</h2>
        <div class="rocket-cards row justify-content-between">
          <% user_rockets = current_user.rockets %>
          <% user_rockets.each do |rocket| %>
            <div class="rocket-card">
              <%= cl_image_tag rocket.photo.key, height: 150, width: 150 if rocket.photo.attached? %>
              <div class="rocket-card-content">
                <div class="rocket-basic-info">
                  <h5><%= rocket.name %></h5>
                  <h5><%= rocket.address %></h5>
                </div>
                <p><%= rocket.description %></p>
                <div class="rocket-capacity-price">
                  <i class="material-icons mr-2">Capacity</i><%= rocket.capacity%>;
                  <i class="material-icons mr-2">£</i><%= rocket.price %>;
                  <i class="material-icons mr-2">Range: </i><%= rocket.range %>;
                  <i class="material-icons mr-2">Power: </i><%= rocket.power %>
                </div>
                <div class="rocket-actions">
                  <%= link_to 'Edit', edit_rocket_path(rocket), class: 'ml-3 text-primary' %>
                  <%= link_to "Remove", rocket_path(rocket), method: :delete, data: { confirm: "Are you sure?" }, class: 'ml-3 text-danger' %>
                </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UberX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <div class="container home"> %>
  <div class="page-container">
    <main class="site_content">
      <div class="banner-home">
        <div class="banner_inner_content">
          <h1>{s}UBER.</h1>
          <h1>Book your rocket in minutes</h1>
          <p>Be on your way to your favorite Galaxy. Captain optional.</p>
          <%= link_to "CHECK OUR ROCKETS", rockets_path, class: "btn btn-flat" %>
        </div>
      </div>

      <div class="row">
        <div class="cards-home">
          <div class="card-home">
            <h2 class="funny__heading">Best prices in the galaxy.</h2>
          </div>
          <div class="card-home">
            <h2 class="funny__heading">See some aliens.</h2>
          </div>
          <div class="card-home">
            <h2 class="funny__heading">Travel at your own risk.</h2>
          </div>
            <div class="card-home">
            <h2 class="funny__heading">One way discounts.</h2>
          </div>
        </div>
      </div>
    </main>
  </div>
<%# </div> %>

app/views/rockets/_form.html.erb
<%# <div class="form-rocket"> %>
  <%= simple_form_for @rocket do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :capacity %>
    <%= f.input :range %>
    <%= f.input :power %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
<%# </div> %>

app/views/rockets/_mapbox.html.erb
<h5><%= link_to rocket.name, rocket_path(rocket) %></h5>
<p><%= rocket.address %></p>

app/views/rockets/edit.html.erb
<div class="banner edit">
</div>

<div class="container mt-4">
  <div class="row edit">
    <div class="col-6 m-auto">
      <div class="form-rocket">
        <h1>Update rocket</h1>
        <div class="mt-3">
          <%= render "form", rocket: @rocket %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rockets/index.html.erb
<div class="top-container">
  <div class="row rockets">
    <h2>Discover all our rockets</h2>
  </div>

  <div class="row rockets-search">
    <div class="search col-4">
      <%= form_tag rockets_path, method: :get do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a rocket"
          %>
          <button name="button" type="submit" class="btn btn-ghost">
            <i class="fas fa-search"></i>
          </button>
          <%# <%= submit_tag "Search", class: "btn btn-ghost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="main-container">
  <div class="row rockets">
    <div class="col-6 rocket-cards">
      <% @rockets.each do |rocket| %>
        <div class="rocket-card">
          <%= cl_image_tag rocket.photo.key, height: 150, width: 200 if rocket.photo.attached? %>
          <div class="rocket-card-content">
            <div class="rocket-basic-info">
              <h5><%= rocket.name %></h5>
              <p class="rocket_address"><%= rocket.address %></p>
            </div>

            <div class="rocket-capacity-price">
              <i class="material-icons mr-2">Capacity</i><%= rocket.capacity %>;
              <i class="material-icons mr-2">    Daily rate £</i><%= rocket.price %>
            </div>

            <div class="rocket-actions">
              <%= link_to 'More info', rocket_path(rocket) %>
            </div>
          </div>
        </div>
      <% end %>
   </div>

   <div class="col-6" id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/rockets/new.html.erb
<div class="banner new">
</div>

<div class="container mt-4">
  <div class="row new">
    <div class="col-6 m-auto">
      <div class="form-rocket">
        <h1>Add a new rocket</h1>
        <div class="mt-3">
          <%= render "form", rocket: @rocket %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rockets/show.html.erb
<div class="banner show">
</div>
<div class="container show">
  <div class="row">
    <div class="rocket-info col-6">
      <div class="rocket-show-card">
        <h5><b><%= @rocket.name %></b></h5>
        <p>Rocket launch site: <%= @rocket.address %></p>
        <%= cl_image_tag @rocket.photo.key, height: 300, width: 520 if @rocket.photo.attached? %>
      </div>
      <div class="rocket-show-card">
        <p class="rocket-show-description"><%= @rocket.description %></p>
      </div>
      <div class="rocket-show-card">
        <%= link_to "Back to all rockets", rockets_path %>
      </div>
    </div>

    <div class="rocket-spec col-3">
      <div class="rocket-show-card">
        <br>
        <br>
        <br>
        <%# <i class="fa-solid fa-users"></i><%= @rocket.capacity %>
        <p><b>Capacity: </b><%= @rocket.capacity %> humans</p>
        <i class="fa-solid fa-circle-dollar"></i>
        <p><b>Price:</b> £<%= @rocket.price %> / day</p>
        <p><b>Range: </b><%= @rocket.range %> light years</p>
        <p><b>Power: </b><%= @rocket.power %> horses</p>
      </div>
    </div>

    <div class="booking col-3">
      <div class="rocket-booking">
        <h5>Book this rocket</h5>
        <%= render 'bookings/form', rocket: @rocket, booking: @booking %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a class="foot-link" href="#"><i class="fab fa-instagram"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-facebook"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-twitter"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyrights">
    <a class="footer-copyright" href="#">About us</a>
    <a class="footer-copyright" href="#">Terms</a>
    <a class="footer-copyright" href="#">Privacy</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dajifvnn5/image/upload/v1644686099/logo2.svg_z4sj5c.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Rockets", rockets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Rocket", new_rocket_path(@rocket), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Account", bookings_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item active">
            <%= link_to "Log Out", rel="nofollow" data-method="delete" root_path, class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dajifvnn5/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1644073202/UberX_front_image_nfk3o3.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# <%= @user.email, class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Rockets", rockets_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>